#!/bin/bash

if [ -d "/c/" ]; then
	echo "battery status(Windows)..."
    	percent=$(wmic path win32_battery get estimatedchargeremaining | tr -d '\r' | awk 'NR==2 {print $1}')
    	echo "current battery precent: ${percent}%"
else
    echo "battery status(Linux)..."
    if command -v acpi &> /dev/null; then
        acpi -b
    elif [ -f /sys/class/power_supply/BAT0/capacity ]; then
        percent=$(cat /sys/class/power_supply/BAT0/capacity)
        status=$(cat /sys/class/power_supply/BAT0/status)
        echo "battery precent: ${percent}% (${status})"
    else
       echo "cant read battery info status."
    fi
fi
