#!/bin/bash

read -p "Hello, please enter the name of the process you want to kill: " process

if [ -z "$process" ]; then
	echo "process wasn't typed."
	exit 1
fi  

read -p "do you really want to kill $process? yes/no: " answer

if [ "$answer" == "yes" ]; then
	echo "trying to kill $process ..."
	pkill -f "$process"
	if [ $? -eq 0 ]; then
		echo "$process sucessfully killed!"
	else
		echo "$process does not exist or you dont have premission to kill it"
	fi
else
	echo "aborting process..."
	exit 1
fi


