#!/bin/bash

if [ -d "/c/" ]; then
    	echo "windows operating system detected."
	root_path="/c/"

else
	echo "linux operating system detected."
    	root_path="/"
fi

echo "showing files disk usage...."

du -h "$root_path" 2>/dev/null

echo "finished..."

